name: MeloTTS Indonesia

on:
  workflow_dispatch:

jobs:
  tts:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install ffmpeg
        run: |
          sudo apt update
          sudo apt install -y ffmpeg

      - name: Install torch
        run: |
          pip install torch==2.3.1 torchaudio==2.3.1

      - name: Install MeloTTS
        run: |
          pip install git+https://github.com/myshell-ai/MeloTTS.git
          pip install unidic
          python -m unidic download

      - name: Run TTS
        run: |
          python main.py

      - uses: actions/upload-artifact@v4
        with:
          name: hasil-audio
          path: output.wav
